---- Procedimientos, Funciones y Vistas asociadas a la tabla relacional PRODUCTO_CATEGORIAS-----

/* ============================================================
   PROYECTO: RetailMan
   MODULO   : PRODUCTOS-CATEGORIAS
   REQ 4   : Asignar Productos a Categorias
   Autor    : Catalina Mora
   Motor    : Oracle PL/SQL
============================================================ */


----- FUNCIONES -----

CREATE OR REPLACE FUNCTION FN_EXISTE_PRODUCTO_CATEGORIA(
    P_PRODUCT_ID PRODUCTO_CATEGORIA.PRODUCT_ID%TYPE,
    P_CATEGORY_ID PRODUCTO_CATEGORIA.CATEGORY_ID%TYPE
)
RETURN NUMBER
AS
    V_TOTAL NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO V_TOTAL
    FROM PRODUCTO_CATEGORIA
    WHERE PRODUCT_ID = P_PRODUCT_ID
    AND CATEGORY_ID = P_CATEGORY_ID;

    RETURN V_TOTAL;

END;
/
-- Valida que una asociación entre producto y categoría no se encuentre registrada.



----- PROCEDIMIENTOS-------

CREATE OR REPLACE PROCEDURE SP_ASIGNAR_PRODUCTO_CATEGORIA(
    P_PRODUCT_ID PRODUCTO_CATEGORIA.PRODUCT_ID%TYPE,
    P_CATEGORY_ID PRODUCTO_CATEGORIA.CATEGORY_ID%TYPE
)
AS
BEGIN

    IF FN_EXISTE_PRODUCTO_CATEGORIA(
        P_PRODUCT_ID,
        P_CATEGORY_ID
    ) > 0 THEN

        RAISE_APPLICATION_ERROR(
            -20004,
            'La asociación ya existe'
        );

    END IF;

    INSERT INTO PRODUCTO_CATEGORIA(
        PRODUCT_ID,
        CATEGORY_ID
    )
    VALUES(
        P_PRODUCT_ID,
        P_CATEGORY_ID
    );

    COMMIT;

END;
/



CREATE OR REPLACE PROCEDURE SP_CONSULTAR_PRODUCTO_CATEGORIA(
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN

    OPEN P_CURSOR FOR

    SELECT
        S.SKU_CODE,
        S.DESCRIPTION,
        C.CODE AS CODIGO_CATEGORIA,
        C.NAME AS CATEGORIA
    FROM PRODUCTO_CATEGORIA PC
    INNER JOIN SKU S
        ON PC.PRODUCT_ID = S.PRODUCT_ID
    INNER JOIN CATEGORIA C
        ON PC.CATEGORY_ID = C.CATEGORY_ID;

END;
/



CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PRODUCTO_CATEGORIA(
    P_PRODUCT_ID PRODUCTO_CATEGORIA.PRODUCT_ID%TYPE,
    P_CATEGORY_ID PRODUCTO_CATEGORIA.CATEGORY_ID%TYPE
)
AS
BEGIN

    DELETE FROM PRODUCTO_CATEGORIA
    WHERE PRODUCT_ID = P_PRODUCT_ID
    AND CATEGORY_ID = P_CATEGORY_ID;

    COMMIT;

END;
/

--- Elimina la relacion entre el producto y la categoria 



----VISTA------

CREATE OR REPLACE VIEW VW_PRODUCTOS_CATEGORIAS
AS
SELECT
    S.SKU_CODE,
    S.DESCRIPTION,
    C.CODE AS CODIGO_CATEGORIA,
    C.NAME AS CATEGORIA
FROM PRODUCTO_CATEGORIA PC
INNER JOIN SKU S
    ON PC.PRODUCT_ID = S.PRODUCT_ID
INNER JOIN CATEGORIA C
    ON PC.CATEGORY_ID = C.CATEGORY_ID;
/


