CREATE USER RetailMan  IDENTIFIED BY Brain$1234Retail;
GRANT ROL_TOTAL TO RetailMan ;
ALTER USER RetailMan QUOTA UNLIMITED ON DATA;


CREATE TABLE MERCADO(
  market_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iso_code  VARCHAR2(5) NOT NULL,
  name      VARCHAR2(100) NOT NULL,
  UNIQUE (iso_code)
);

COMMENT ON TABLE MERCADO IS 'Mercados/países de operación';
COMMENT ON COLUMN MERCADO.iso_code IS 'Código ISO del país';



CREATE TABLE CANAL(
  channel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       VARCHAR2(40) UNIQUE NOT NULL,
  name       VARCHAR2(120) NOT NULL
);

COMMENT ON TABLE CANAL IS 'Canales comerciales (Supermercado, Club, Discount, etc.)';



CREATE TABLE RETAILER (
  retailer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market_id   NUMBER NOT NULL REFERENCES MERCADO(market_id),
  code        VARCHAR2(60),
  name        VARCHAR2(200) NOT NULL,
  status      VARCHAR2(20) DEFAULT 'ACTIVE'
               CHECK (status IN ('ACTIVE','INACTIVE')),
  UNIQUE (market_id, code)
);

COMMENT ON TABLE RETAILER IS 'Retailers (operadores) por mercado';
COMMENT ON COLUMN RETAILER.code IS 'Código del retailer dentro del mercado';



CREATE TABLE FORMATO (
  format_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code      VARCHAR2(40) UNIQUE NOT NULL,
  name      VARCHAR2(120) NOT NULL
);

COMMENT ON TABLE FORMATO IS 'Formatos de tienda (Descuentos, Supermercado, Club, etc.)';



CREATE TABLE RETAILER_FORMATO (
  retailer_format_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retailer_id        NUMBER NOT NULL REFERENCES RETAILER(retailer_id),
  format_id          NUMBER NOT NULL REFERENCES FORMATO(format_id),
  name               VARCHAR2(200) NOT NULL,
  status             VARCHAR2(20) DEFAULT 'ACTIVE'
                     CHECK (status IN ('ACTIVE','INACTIVE')),
  UNIQUE (retailer_id, format_id, name)
);

COMMENT ON TABLE RETAILER_FORMATO IS 'Relación entre retailer y sus formatos';



CREATE TABLE FABRICANTE (
  manufacturer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR2(200) NOT NULL,
  country_code    VARCHAR2(5)
);

COMMENT ON TABLE FABRICANTE IS 'Fabricantes propietarios de marcas';



CREATE TABLE MARCA (
  brand_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer_id NUMBER REFERENCES FABRICANTE(manufacturer_id),
  name            VARCHAR2(150) NOT NULL,
  status          VARCHAR2(20) DEFAULT 'ACTIVE'
                  CHECK (status IN ('ACTIVE','INACTIVE')),
  UNIQUE (manufacturer_id, name)
);

COMMENT ON TABLE MARCA IS 'Marcas comerciales';



CREATE TABLE CATEGORIA(
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR2(60) UNIQUE NOT NULL,
  name        VARCHAR2(150) NOT NULL,
  level_no    NUMBER NOT NULL,
  parent_id   NUMBER REFERENCES CATEGORIA(category_id),
  status      VARCHAR2(20) DEFAULT 'ACTIVE'
              CHECK (status IN ('ACTIVE','INACTIVE'))
);

COMMENT ON TABLE CATEGORIA IS 'Árbol de categorías (jerárquico)';



CREATE TABLE SKU (
  product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_code      VARCHAR2(80) UNIQUE,
  brand_id      NUMBER REFERENCES MARCA(brand_id),
  description   VARCHAR2(400) NOT NULL,
  net_content   NUMBER,
  uom           VARCHAR2(20),
  presentation  VARCHAR2(60),

  height        NUMBER(10,3),
  width         NUMBER(10,3),
  depth         NUMBER(10,3),
  dim_uom       VARCHAR2(10),

  net_weight    NUMBER(10,3),
  gross_weight  NUMBER(10,3),
  weight_uom    VARCHAR2(10),

  status        VARCHAR2(20) DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SKU IS 'Productos/SKUs comercializados';



CREATE TABLE PRODUCTOS_GTIN (
  product_id      NUMBER NOT NULL,
  gtin            VARCHAR2(20) NOT NULL,
  CONSTRAINT pk_productos_gtin PRIMARY KEY (product_id, gtin),
  CONSTRAINT fk_productos_gtin_sku
    FOREIGN KEY (product_id) REFERENCES SKU(product_id)
);

COMMENT ON TABLE PRODUCTOS_GTIN IS 'GTINs asociadas a cada SKU';


CREATE TABLE PRODUCTO_CATEGORIA (
  product_id  NUMBER NOT NULL REFERENCES SKU(product_id),
  category_id NUMBER NOT NULL REFERENCES CATEGORIA(category_id),
  PRIMARY KEY (product_id, category_id)
);

COMMENT ON TABLE PRODUCTO_CATEGORIA IS 'Asignación de SKU a categoría con vigencia';



CREATE TABLE PUNTO_VENTA (
  store_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  retailer_id  NUMBER NOT NULL REFERENCES RETAILER(retailer_id),
  market_id    NUMBER NOT NULL REFERENCES MERCADO(market_id),
  channel_id   NUMBER REFERENCES CANAL(channel_id),

  code         VARCHAR2(50),
  name         VARCHAR2(200) NOT NULL,
  zone         VARCHAR2(100),
  address      VARCHAR2(300),

  status       VARCHAR2(20) DEFAULT 'ACTIVE'
               CHECK (status IN ('ACTIVE','INACTIVE')),

  UNIQUE (retailer_id, code)
);

COMMENT ON TABLE PUNTO_VENTA IS 'Puntos de venta físicos (tiendas)';
COMMENT ON COLUMN PUNTO_VENTA.name IS 'Nombre del punto de venta';
COMMENT ON COLUMN PUNTO_VENTA.zone IS 'Zona geográfica o comercial';
COMMENT ON COLUMN PUNTO_VENTA.code IS 'Código único dentro del retailer';




